const ACTION_TYPE_ADD = 'ACTION_TYPE_ADD';
const ACTION_TYPE_SELECT_CHANGE = 'ACTION_TYPE_SELECT_CHANGE';
const ACTION_TYPE_ON_SELECT_CHANGE = 'ACTION_TYPE_ON_SELECT_CHANGE';
const ACTION_TYPE_DELETE = 'ACTION_TYPE_DELETE';

export {
    ACTION_TYPE_ADD,
    ACTION_TYPE_SELECT_CHANGE,
    ACTION_TYPE_ON_SELECT_CHANGE,
    ACTION_TYPE_DELETE,
}